import statistics as st
import pandas as pd
df = pd.read_csv("scores.csv")
df.describe(include='all')
print(df)

# max
print('\n******* MAX *******')
max1 = df['Test 1'].max()
print('\nTest 1 Max Score: ' + str(max1))
max2 = df['Test 2'].max()
print('\nTest 2 Max Score: ' + str(max2))
max3 = df['Test 3'].max()
print('\nTest 3 Max Score: ' + str(max3))
max4 = df['Project'].max()
print('\nProject Max Score: ' + str(max4))
# min
print('\n******* MIN *******')
min1 = df['Test 1'].min()
print('\nTest 1 Min Score: ' + str(min1))
min2 = df['Test 2'].min()
print('\nTest 2 Min Score: ' + str(min2))
min3 = df['Test 3'].min()
print('\nTest 3 Min Score: ' + str(min3))
min4 = df['Project'].min()
print('\nProject Min Score: ' + str(min4))
# range (max-min)
print('\n******* RANGE *******')
print('\n Test 1 Range: ' + str(max1-min1))
print('\n Test 2 Range: ' + str(max2-min2))
print('\n Test 3 Range: ' + str(max3-min3))
print('\n Project Range: ' + str(max4-min4))
# mean
print('\n******* MEAN *******')
mean1 = df['Test 1'].mean()
print('\nTest 1 Mean Score: ' + str(mean1))
mean2 = df['Test 2'].mean()
print('\nTest 2 Mean Score: ' + str(mean2))
mean3 = df['Test 3'].mean()
print('\nTest 3 Mean Score: ' + str(mean3))
mean4 = df['Project'].mean()
print('\nProject Mean Score: ' + str(mean4))
# variance
print('\n******* VARIANCE *******')
var1 = df['Test 1'].var()
print('\n Test 1 Variance: ' + str(var1))
var2 = df['Test 2'].var()
print('\n Test 2 Variance: ' + str(var2))
var3 = df['Test 3'].var()
print('\n Test 3 Variance: ' + str(var3))
var4 = df['Project'].var()
print('\n Project Variance: ' + str(var4))
# standard deviation
print('\n******* STANDARD DEVIATION *******')
std1 = df['Test 1'].std()
print('\n Test 1 Standard Deviation: ' + str(std1))
std2 = df['Test 2'].std()
print('\n Test 2 Standard Deviation: ' + str(std2))
std3 = df['Test 3'].std()
print('\n Test 3 Standard Deviation: ' + str(std3))
std4 = df['Project'].std()
print('\n Project Standard Deviation: ' + str(std4))
